# Generated by Django 4.2.30 on 2026-06-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_sub_state_issue_sub_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sub_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_state_issue', to='db.substate'),
        ),
    ]
