# Generated by Codex for private module visibility

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_project_issue_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
    ]
