# Generated by Django 4.2.30 on 2026-07-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_module_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleIssueField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('field_type', models.CharField(choices=[('single_select', 'Single-select text'), ('multi_select', 'Multi-select text'), ('single_member', 'Single-select member'), ('multi_member', 'Multi-select member'), ('date', 'Date'), ('date_range', 'Date range'), ('plain_text', 'Plain text')], max_length=32)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_fields', to='db.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_fields', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_fields', to='db.workspace')),
            ],
            options={
                'db_table': 'module_issue_fields',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ModuleIssueFieldOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.moduleissuefield')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_field_options', to='db.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_options', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_options', to='db.workspace')),
            ],
            options={
                'db_table': 'module_issue_field_options',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ModuleIssueFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_values', to='db.moduleissuefield')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_field_value_rows', to='db.issue')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_field_values', to='db.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_values', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_values', to='db.workspace')),
            ],
            options={
                'db_table': 'module_issue_field_values',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModuleIssueFieldValueUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_value_users', to='db.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_value_users', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_values', to=settings.AUTH_USER_MODEL)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_users', to='db.moduleissuefieldvalue')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_value_users', to='db.workspace')),
            ],
            options={
                'db_table': 'module_issue_field_value_users',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModuleIssueFieldValueOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_value_options', to='db.module')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_values', to='db.moduleissuefieldoption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_value_options', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='db.moduleissuefieldvalue')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_issue_field_value_options', to='db.workspace')),
            ],
            options={
                'db_table': 'module_issue_field_value_options',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='moduleissuefieldvalueuser',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('value', 'user'), name='module_issue_field_value_user_unique_value_user_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='moduleissuefieldvalueoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('value', 'option'), name='module_issue_field_value_option_unique_value_option_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='moduleissuefieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'field'), name='module_issue_field_value_unique_issue_field_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='moduleissuefieldoption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('field', 'value'), name='module_issue_field_option_unique_field_value_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='moduleissuefield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('module', 'name'), name='module_issue_field_unique_module_name_when_not_deleted'),
        ),
    ]
