# Generated by Django 4.2.30 on 2026-07-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0126_module_issue_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueview",
            name="source_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_views",
                to="db.module",
            ),
        ),
    ]
